language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
 - npm install -g gulp

script:
  - hexo d

# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "Bruce"
#   - git config user.email "444048170@qq.com"
#   - git add .
#   - git commit -m "Update docs"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: https://github.com/BruceYuj/BruceYuj.github.io